[build]
builder = "dockerfile"

[deploy]
startCommand = "node src/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.env]
CI = "false"
NODE_OPTIONS = "--max-old-space-size=4096"
NODE_ENV = "production"
