[build]
# Build both frontend and backend using the unified Dockerfile
builder = "dockerfile"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8080"
NODE_ENV = "production"

[build.env]
CI = "false"
NODE_OPTIONS = "--max-old-space-size=4096"
NODE_ENV = "production"
