[build]
# Build both frontend and backend using the unified Dockerfile
builder = "dockerfile"

[deploy]
startCommand = "./railway-start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.env]
CI = "false"
NODE_OPTIONS = "--max-old-space-size=4096"
NODE_ENV = "production"
